#!/usr/bin/env bash
set -x
function s.upgrade
{
	s.stop
	vagrant ssh -c "sudo su -l root -c '/var/www/html/phabricator-server/phabricator/bin/storage upgrade --force'"
	s.start
}
function es.index
{
	vagrant ssh -c "sudo su -l root -c '/var/www/html/phabricator-server/phabricator/bin/config set search.elastic.host \"http://10.0.2.2:9200\"'"
	vagrant ssh -c "sudo su -l root -c '/var/www/html/phabricator-server/phabricator/bin/search index --all'"
}

function s.config
{
	vagrant ssh -c "sudo su -l root -c '/var/www/html/phabricator-server/phabricator/bin/config set phabricator.timezone \"Asia/Shanghai\"'"
	vagrant ssh -c "sudo su -l root -c '/var/www/html/phabricator-server/phabricator/bin/config set storage.local-disk.path \"/opt/files\"'"
	vagrant ssh -c "sudo su -l root -c '/var/www/html/phabricator-server/phabricator/bin/config set phabricator.base-uri \"http://p.gnuhub.com\"'"
	# 修正文件上传大小问题 https://github.com/gnuhub/ansible.ubuntu.phabricator/issues/21
	vagrant ssh -c "sudo sed -i 's/^post_max_size.*/post_max_size = 20000M/g' /etc/php5/apache2/php.ini"
	vagrant ssh -c "sudo sed -i 's/^upload_max_filesize.*/upload_max_filesize = 20000M/g' /etc/php5/apache2/php.ini"
	s.stop
	s.start
}
function s.restart
{
	s.stop
	s.start
}
function s.start
{
	vagrant ssh -c "sudo service apache2 start"
	vagrant ssh -c "sudo /var/www/html/phabricator-server/phabricator/bin/phd restart"
}

function s.stop
{
	vagrant ssh -c "sudo service apache2 stop"
	vagrant ssh -c "sudo /var/www/html/phabricator-server/phabricator/bin/phd stop"
	sleep 3
}

function all
{
	s.config
	s.upgrade
	es.index
}

${1}